/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface Paths {
  "/connect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Deprecated since 01.10.2024, please use http://localhost:3000/api/oauth/soundcloud instead. Use Authorize button in Swagger UI to see it in action.
     * @deprecated
     * @description <h3>Security Advice</h3>
     *     * [OAuth Authorization Code flow](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics-16#section-2.1.1) (`response_type=code`) is the only allowed method of authorization.
     *     * Use the `state` parameter for [CSRF protection](https://tools.ietf.org/html/draft-ietf-oauth-security-topics-16#section-4.7). Pass a sufficient  random nonce here and verify this nonce again after retrieving the token.
     */
    get: {
      parameters: {
        query: {
          /**
           * @description The client id belonging to your application
           * @example some client
           */
          client_id: components["parameters"]["client_id"];
          /**
           * @description The redirect uri you have configured for your application
           * @example https://soundcloud.com
           */
          redirect_uri: components["parameters"]["redirect_uri"];
          /**
           * @description Support only the Authorization Code Flow
           * @example code
           */
          response_type: components["parameters"]["response_type"];
          /**
           * @description Any value included here will be appended to the redirect URI. Use this for CSRF protection.
           * @example encrypted_session_info
           */
          state?: components["parameters"]["state"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Redirect to connect portal */
        302: {
          headers: {
            /** @description Redirect to connect portal "https://secure.soundcloud.com/connect" */
            Location?: string;
            [name: string]: unknown;
          };
          content?: never;
        };
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oauth2/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Deprecated since 01.10.2024, please use https://secure.soundcloud.com/oauth/token instead. Use Authorize button in Swagger UI to see it in action.
     * @deprecated
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/x-www-form-urlencoded": components["schemas"]["OAuthToken"];
          "multipart/form-data": components["schemas"]["OAuthToken"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json; charset=utf-8": unknown;
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns the authenticated user’s information. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Me"];
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/activities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns the authenticated user's activities. */
    get: {
      parameters: {
        query?: {
          /** @description Filters content by level of access the user (logged in or anonymous) has to the track. The result list will include only tracks with the specified access. Include all options if you'd like to see all possible tracks. See `Track#access` schema for more details. */
          access?: components["parameters"]["access"];
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Activities"];
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/activities/all/own": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Recent the authenticated user's activities. */
    get: {
      parameters: {
        query?: {
          /** @description Filters content by level of access the user (logged in or anonymous) has to the track. The result list will include only tracks with the specified access. Include all options if you'd like to see all possible tracks. See `Track#access` schema for more details. */
          access?: components["parameters"]["access"];
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Activities"];
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/activities/tracks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns the authenticated user's recent track related activities. */
    get: {
      parameters: {
        query?: {
          /** @description Filters content by level of access the user (logged in or anonymous) has to the track. The result list will include only tracks with the specified access. Include all options if you'd like to see all possible tracks. See `Track#access` schema for more details. */
          access?: components["parameters"]["access"];
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Activities"];
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/likes/tracks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a list of favorited or liked tracks of the authenticated user. */
    get: {
      parameters: {
        query?: {
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
          /** @description Filters content by level of access the user (logged in or anonymous) has to the track. The result list will include only tracks with the specified access. Include all options if you'd like to see all possible tracks. See `Track#access` schema for more details. */
          access?: components["parameters"]["access_explicit"];
          /**
           * @description Returns paginated collection of items (recommended, returning a list without pagination is deprecated and should not be used)
           * @example true
           */
          linked_partitioning?: components["parameters"]["linked_partitioning"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Tracks"];
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/likes/playlists": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a list of favorited or liked playlists of the authenticated user. */
    get: {
      parameters: {
        query?: {
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
          /**
           * @description Returns paginated collection of items (recommended, returning a list without pagination is deprecated and should not be used)
           * @example true
           */
          linked_partitioning?: components["parameters"]["linked_partitioning"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Playlists"];
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/followings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a list of users who are followed by the authenticated user. */
    get: {
      parameters: {
        query?: {
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
          /**
           * @deprecated
           * @description Offset of first result. Deprecated, use `linked_partitioning` instead.
           * @example 0
           */
          offset?: components["parameters"]["offset"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Users"];
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/followings/tracks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a list of recent tracks from users followed by the authenticated user. */
    get: {
      parameters: {
        query?: {
          /** @description Filters content by level of access the user (logged in or anonymous) has to the track. The result list will include only tracks with the specified access. Include all options if you'd like to see all possible tracks. See `Track#access` schema for more details. */
          access?: components["parameters"]["access"];
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
          /**
           * @deprecated
           * @description Offset of first result. Deprecated, use `linked_partitioning` instead.
           * @example 0
           */
          offset?: components["parameters"]["offset"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["TracksList"];
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/followings/{user_urn}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns a user who is followed by the authenticated user. (use /users/{user_urn} instead, to fetch the user details)
     * @deprecated
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /**
           * @description SoundCloud User id
           * @example soundcloud:users:948745750
           */
          user_urn: components["parameters"]["user_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["User"];
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    /** Follows a user. */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /**
           * @description SoundCloud User id
           * @example soundcloud:users:743372812
           */
          user_urn: components["parameters"]["user_urn_to_follow"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Successful"];
        201: components["responses"]["User"];
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    post?: never;
    /** Deletes a user who is followed by the authenticated user. */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /**
           * @description SoundCloud User id
           * @example soundcloud:users:743372812
           */
          user_urn: components["parameters"]["user_urn_to_follow"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json; charset=utf-8": unknown;
          };
        };
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
        422: components["responses"]["UnprocessableEntity"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/followers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a list of users who are following the authenticated user. */
    get: {
      parameters: {
        query?: {
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Users"];
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/followers/{follower_urn}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns a user who is following the authenticated user. (use /users/{user_urn} instead, to fetch the user details)
     * @deprecated
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /**
           * @description SoundCloud User id to denote a Follower
           * @example soundcloud:users:743372812
           */
          follower_urn: components["parameters"]["follower_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["User"];
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/playlists": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns user’s playlists (sets).
     * @description Returns playlist info, playlist tracks and tracks owner info.
     */
    get: {
      parameters: {
        query?: {
          /**
           * @description A boolean flag to request a playlist with or without tracks. Default is `true`.
           * @example true
           */
          show_tracks?: components["parameters"]["show_tracks"];
          /**
           * @description Returns paginated collection of items (recommended, returning a list without pagination is deprecated and should not be used)
           * @example true
           */
          linked_partitioning?: components["parameters"]["linked_partitioning"];
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Playlists"];
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/tracks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a list of user's tracks. */
    get: {
      parameters: {
        query?: {
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
          /**
           * @description Returns paginated collection of items (recommended, returning a list without pagination is deprecated and should not be used)
           * @example true
           */
          linked_partitioning?: components["parameters"]["linked_partitioning"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Tracks"];
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tracks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Performs a track search based on a query */
    get: {
      parameters: {
        query?: {
          /**
           * @description search
           * @example hello
           */
          q?: components["parameters"]["q"];
          /**
           * @description A comma separated list of track ids to filter on
           * @example 1,2,3
           */
          ids?: components["parameters"]["ids"];
          /**
           * @description A comma separated list of track urns to filter on
           * @example soundcloud:tracks:1,soundcloud:tracks:2,soundcloud:tracks:3
           */
          urns?: components["parameters"]["urns"];
          /**
           * @description A comma separated list of genres
           * @example Pop,House
           */
          genres?: components["parameters"]["genres"];
          /**
           * @description A comma separated list of tags
           * @example test
           */
          tags?: components["parameters"]["tags"];
          /** @description Return tracks with a specified bpm[from], bpm[to] */
          bpm?: components["parameters"]["bpm"];
          /** @description Return tracks within a specified duration range */
          duration?: components["parameters"]["duration"];
          /** @description (yyyy-mm-dd hh:mm:ss) return tracks created within the specified dates */
          created_at?: components["parameters"]["created_at"];
          /** @description Filters content by level of access the user (logged in or anonymous) has to the track. The result list will include only tracks with the specified access. Include all options if you'd like to see all possible tracks. See `Track#access` schema for more details. */
          access?: components["parameters"]["access"];
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
          /**
           * @deprecated
           * @description Offset of first result. Deprecated, use `linked_partitioning` instead.
           * @example 0
           */
          offset?: components["parameters"]["offset"];
          /**
           * @description Returns paginated collection of items (recommended, returning a list without pagination is deprecated and should not be used)
           * @example true
           */
          linked_partitioning?: components["parameters"]["linked_partitioning"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Tracks"];
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Uploads a new track. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "multipart/form-data": components["schemas"]["TrackDataRequest"] & unknown;
          "multipart/x-www-form-urlencoded": components["schemas"]["TrackDataRequest"] & unknown;
        };
      };
      responses: {
        201: components["responses"]["Track"];
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        422: components["responses"]["UnprocessableEntity"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playlists": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Performs a playlist search based on a query */
    get: {
      parameters: {
        query?: {
          /**
           * @description search
           * @example hello
           */
          q?: components["parameters"]["q"];
          /** @description Filters content by level of access the user (logged in or anonymous) has to the track. The result list will include only tracks with the specified access. Include all options if you'd like to see all possible tracks. See `Track#access` schema for more details. */
          access?: components["parameters"]["access"];
          /**
           * @description A boolean flag to request a playlist with or without tracks. Default is `true`.
           * @example true
           */
          show_tracks?: components["parameters"]["show_tracks"];
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
          /**
           * @deprecated
           * @description Offset of first result. Deprecated, use `linked_partitioning` instead.
           * @example 0
           */
          offset?: components["parameters"]["offset"];
          /**
           * @description Returns paginated collection of items (recommended, returning a list without pagination is deprecated and should not be used)
           * @example true
           */
          linked_partitioning?: components["parameters"]["linked_partitioning"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Playlists"];
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    /** Creates a playlist. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Create Playlist request */
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateUpdatePlaylistRequest"];
          "multipart/form-data": components["schemas"]["CreateUpdatePlaylistFormRequest"] & unknown;
        };
      };
      responses: {
        201: components["responses"]["Playlist"];
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Performs a user search based on a query */
    get: {
      parameters: {
        query?: {
          /**
           * @description search
           * @example hello
           */
          q?: components["parameters"]["q"];
          /**
           * @description A comma separated list of track ids to filter on
           * @example 1,2,3
           */
          ids?: components["parameters"]["ids"];
          /**
           * @description A comma separated list of track urns to filter on
           * @example soundcloud:tracks:1,soundcloud:tracks:2,soundcloud:tracks:3
           */
          urns?: components["parameters"]["urns"];
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
          /**
           * @deprecated
           * @description Offset of first result. Deprecated, use `linked_partitioning` instead.
           * @example 0
           */
          offset?: components["parameters"]["offset"];
          /**
           * @description Returns paginated collection of items (recommended, returning a list without pagination is deprecated and should not be used)
           * @example true
           */
          linked_partitioning?: components["parameters"]["linked_partitioning"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Users"];
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playlists/{playlist_urn}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a playlist. */
    get: {
      parameters: {
        query?: {
          /** @description A secret token to fetch private playlists/tracks */
          secret_token?: components["parameters"]["secret_token"];
          /** @description Filters content by level of access the user (logged in or anonymous) has to the track. The result list will include only tracks with the specified access. Include all options if you'd like to see all possible tracks. See `Track#access` schema for more details. */
          access?: components["parameters"]["access"];
          /**
           * @description A boolean flag to request a playlist with or without tracks. Default is `true`.
           * @example true
           */
          show_tracks?: components["parameters"]["show_tracks"];
        };
        header?: never;
        path: {
          /**
           * @description SoundCloud playlist id
           * @example soundcloud:playlists:1212781357
           */
          playlist_urn: components["parameters"]["playlist_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Playlist"];
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
      };
    };
    /** Updates a playlist. */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /**
           * @description SoundCloud playlist id
           * @example soundcloud:playlists:10
           */
          playlist_urn: components["parameters"]["fake_playlist_urn"];
        };
        cookie?: never;
      };
      /** @description Playlist payload */
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateUpdatePlaylistRequest"];
        };
      };
      responses: {
        200: components["responses"]["Playlist"];
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    post?: never;
    /** Deletes a playlist. */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /**
           * @description SoundCloud playlist id
           * @example soundcloud:playlists:10
           */
          playlist_urn: components["parameters"]["fake_playlist_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        404: components["responses"]["NotFound"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playlists/{playlist_urn}/tracks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns tracks under a playlist. */
    get: {
      parameters: {
        query?: {
          /** @description A secret token to fetch private playlists/tracks */
          secret_token?: components["parameters"]["secret_token"];
          /** @description Filters content by level of access the user (logged in or anonymous) has to the track. The result list will include only tracks with the specified access. Include all options if you'd like to see all possible tracks. See `Track#access` schema for more details. */
          access?: components["parameters"]["access"];
          /**
           * @description Returns paginated collection of items (recommended, returning a list without pagination is deprecated and should not be used)
           * @example true
           */
          linked_partitioning?: components["parameters"]["linked_partitioning"];
        };
        header?: never;
        path: {
          /**
           * @description SoundCloud playlist id
           * @example soundcloud:playlists:1212781357
           */
          playlist_urn: components["parameters"]["playlist_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Tracks"];
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playlists/{playlist_urn}/reposters": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a collection of playlist's reposters. */
    get: {
      parameters: {
        query?: {
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
        };
        header?: never;
        path: {
          /**
           * @description SoundCloud playlist id
           * @example soundcloud:playlists:1212781357
           */
          playlist_urn: components["parameters"]["playlist_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Users"];
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tracks/{track_urn}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a track. */
    get: {
      parameters: {
        query?: {
          /** @description A secret token to fetch private playlists/tracks */
          secret_token?: components["parameters"]["secret_token"];
        };
        header?: never;
        path: {
          /**
           * @description SoundCloud Track urn
           * @example soundcloud:tracks:308946187
           */
          track_urn: components["parameters"]["track_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Track"];
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    /** Updates a track's information. */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /**
           * @description SoundCloud Track urn
           * @example soundcloud:tracks:308946187
           */
          track_urn: components["parameters"]["track_urn"];
        };
        cookie?: never;
      };
      /** @description Track payload */
      requestBody?: {
        content: {
          "application/json": components["schemas"]["TrackMetadataRequest"];
          "multipart/form-data": components["schemas"]["TrackDataRequest"];
          "multipart/x-www-form-urlencoded": components["schemas"]["TrackDataRequest"];
        };
      };
      responses: {
        200: components["responses"]["Track"];
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
      };
    };
    post?: never;
    /** Deletes a track. */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /**
           * @description SoundCloud Track urn
           * @example soundcloud:tracks:308946187
           */
          track_urn: components["parameters"]["track_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        404: components["responses"]["NotFound"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tracks/{track_urn}/streams": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a track's streamable URLs (needs to keep using authentication) */
    get: {
      parameters: {
        query?: {
          /** @description A secret token to fetch private playlists/tracks */
          secret_token?: components["parameters"]["secret_token"];
        };
        header?: never;
        path: {
          /**
           * @description SoundCloud Track urn
           * @example soundcloud:tracks:308946187
           */
          track_urn: components["parameters"]["track_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Streams"];
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tracks/{track_urn}/comments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns the comments posted on the track(track_urn). */
    get: {
      parameters: {
        query?: {
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
          /**
           * @deprecated
           * @description Offset of first result. Deprecated, use `linked_partitioning` instead.
           * @example 0
           */
          offset?: components["parameters"]["offset"];
          /**
           * @description Returns paginated collection of items (recommended, returning a list without pagination is deprecated and should not be used)
           * @example true
           */
          linked_partitioning?: components["parameters"]["linked_partitioning"];
        };
        header?: never;
        path: {
          /**
           * @description SoundCloud Track urn
           * @example soundcloud:tracks:308946187
           */
          track_urn: components["parameters"]["track_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Comments"];
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    /** Returns the newly created comment on success */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /**
           * @description SoundCloud Track urn
           * @example soundcloud:tracks:308946187
           */
          track_urn: components["parameters"]["track_urn"];
        };
        cookie?: never;
      };
      /** @description Body of a comment */
      requestBody: {
        content: {
          "application/json; charset=utf-8": {
            comment?: {
              /**
               * @description Comment's content
               * @example test comment
               */
              body: string;
              /** @description Timestamp of a comment. String or float representation is supported */
              timestamp?: string | number;
            };
          };
        };
      };
      responses: {
        201: components["responses"]["Comment"];
        422: components["responses"]["UnprocessableEntity"];
        429: components["responses"]["TooManyRequests"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tracks/{track_urn}/favoriters": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a list of users who have favorited or liked the track. */
    get: {
      parameters: {
        query?: {
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
          /**
           * @description Returns paginated collection of items (recommended, returning a list without pagination is deprecated and should not be used)
           * @example true
           */
          linked_partitioning?: components["parameters"]["linked_partitioning"];
        };
        header?: never;
        path: {
          /**
           * @description SoundCloud Track urn
           * @example soundcloud:tracks:308946187
           */
          track_urn: components["parameters"]["track_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Users"];
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tracks/{track_urn}/reposters": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a collection of track's reposters. */
    get: {
      parameters: {
        query?: {
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
        };
        header?: never;
        path: {
          /**
           * @description SoundCloud Track urn
           * @example soundcloud:tracks:308946187
           */
          track_urn: components["parameters"]["track_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Users"];
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tracks/{track_urn}/related": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns all related tracks of track on SoundCloud. */
    get: {
      parameters: {
        query?: {
          /** @description Filters content by level of access the user (logged in or anonymous) has to the track. The result list will include only tracks with the specified access. Include all options if you'd like to see all possible tracks. See `Track#access` schema for more details. */
          access?: components["parameters"]["access"];
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
          /**
           * @deprecated
           * @description Offset of first result. Deprecated, use `linked_partitioning` instead.
           * @example 0
           */
          offset?: components["parameters"]["offset"];
          /**
           * @description Returns paginated collection of items (recommended, returning a list without pagination is deprecated and should not be used)
           * @example true
           */
          linked_partitioning?: components["parameters"]["linked_partitioning"];
        };
        header?: never;
        path: {
          /**
           * @description SoundCloud Track urn
           * @example soundcloud:tracks:308946187
           */
          track_urn: components["parameters"]["track_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Tracks"];
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/resolve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Resolves soundcloud.com and on.soundcloud.com URLs to Resource URLs to use with the API. */
    get: {
      parameters: {
        query: {
          /**
           * @description SoundCloud URL
           * @example https://soundcloud.com/user-434241656
           */
          url: components["parameters"]["url"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        302: components["responses"]["Found"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user_urn}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a user. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /**
           * @description SoundCloud User id
           * @example soundcloud:users:948745750
           */
          user_urn: components["parameters"]["user_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["User"];
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user_urn}/favorites": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns a list of user's favorited or liked tracks. (use /users/:userId/likes/tracks instead, to fetch a user's likes)
     * @deprecated
     */
    get: {
      parameters: {
        query?: {
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
          /**
           * @description Returns paginated collection of items (recommended, returning a list without pagination is deprecated and should not be used)
           * @example true
           */
          linked_partitioning?: components["parameters"]["linked_partitioning"];
        };
        header?: never;
        path: {
          /**
           * @description SoundCloud User id
           * @example soundcloud:users:948745750
           */
          user_urn: components["parameters"]["user_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Tracks"];
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user_urn}/followers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns a list of user’s followers.
     * @description Returns a list of users that follows (user_urn).
     */
    get: {
      parameters: {
        query?: {
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
        };
        header?: never;
        path: {
          /**
           * @description SoundCloud User id
           * @example soundcloud:users:948745750
           */
          user_urn: components["parameters"]["user_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Users"];
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user_urn}/followings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns a list of user’s followings.
     * @description Returns list of users that (user_urn) follows.
     */
    get: {
      parameters: {
        query?: {
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
        };
        header?: never;
        path: {
          /**
           * @description SoundCloud User id
           * @example soundcloud:users:948745750
           */
          user_urn: components["parameters"]["user_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Users"];
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user_urn}/followings/{following_urn}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns a user's following. (use /users/{user_urn} instead, to fetch the user details)
     * @deprecated
     * @description Returns (following_id) that is followed by (user_urn).
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /**
           * @description SoundCloud User id
           * @example soundcloud:users:948745750
           */
          user_urn: components["parameters"]["user_urn"];
          /**
           * @description SoundCloud User id to denote a Following of a user
           * @example soundcloud:users:25219981
           */
          following_urn: components["parameters"]["following_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["User"];
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user_urn}/playlists": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a list of user's playlists. */
    get: {
      parameters: {
        query?: {
          /** @description Filters content by level of access the user (logged in or anonymous) has to the track. The result list will include only tracks with the specified access. Include all options if you'd like to see all possible tracks. See `Track#access` schema for more details. */
          access?: components["parameters"]["access"];
          /**
           * @description A boolean flag to request a playlist with or without tracks. Default is `true`.
           * @example true
           */
          show_tracks?: components["parameters"]["show_tracks"];
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
          /**
           * @description Returns paginated collection of items (recommended, returning a list without pagination is deprecated and should not be used)
           * @example true
           */
          linked_partitioning?: components["parameters"]["linked_partitioning"];
        };
        header?: never;
        path: {
          /**
           * @description SoundCloud User id
           * @example soundcloud:users:948745750
           */
          user_urn: components["parameters"]["user_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Playlists"];
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user_urn}/tracks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a list of user's tracks. */
    get: {
      parameters: {
        query?: {
          /** @description Filters content by level of access the user (logged in or anonymous) has to the track. The result list will include only tracks with the specified access. Include all options if you'd like to see all possible tracks. See `Track#access` schema for more details. */
          access?: components["parameters"]["access"];
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
          /**
           * @description Returns paginated collection of items (recommended, returning a list without pagination is deprecated and should not be used)
           * @example true
           */
          linked_partitioning?: components["parameters"]["linked_partitioning"];
        };
        header?: never;
        path: {
          /**
           * @description SoundCloud User id
           * @example soundcloud:users:948745750
           */
          user_urn: components["parameters"]["user_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Tracks"];
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user_urn}/web-profiles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns list of user's links added to their profile (website, facebook, instagram). */
    get: {
      parameters: {
        query?: {
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
        };
        header?: never;
        path: {
          /**
           * @description SoundCloud User id
           * @example soundcloud:users:948745750
           */
          user_urn: components["parameters"]["user_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["WebProfiles"];
        401: components["responses"]["Unauthorized"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user_urn}/likes/tracks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a list of user's liked tracks. */
    get: {
      parameters: {
        query?: {
          /** @description Filters content by level of access the user (logged in or anonymous) has to the track. The result list will include only tracks with the specified access. Include all options if you'd like to see all possible tracks. See `Track#access` schema for more details. */
          access?: components["parameters"]["access"];
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
          /**
           * @description Returns paginated collection of items (recommended, returning a list without pagination is deprecated and should not be used)
           * @example true
           */
          linked_partitioning?: components["parameters"]["linked_partitioning"];
        };
        header?: never;
        path: {
          /**
           * @description SoundCloud User id
           * @example soundcloud:users:948745750
           */
          user_urn: components["parameters"]["user_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Tracks"];
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user_urn}/likes/playlists": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a list of user's liked playlists. */
    get: {
      parameters: {
        query?: {
          /**
           * @description Number of results to return in the collection.
           * @example 2
           */
          limit?: components["parameters"]["limit"];
          /**
           * @description Returns paginated collection of items (recommended, returning a list without pagination is deprecated and should not be used)
           * @example true
           */
          linked_partitioning?: components["parameters"]["linked_partitioning"];
        };
        header?: never;
        path: {
          /**
           * @description SoundCloud User id
           * @example soundcloud:users:948745750
           */
          user_urn: components["parameters"]["user_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Playlists"];
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/likes/tracks/{track_urn}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Likes a track. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /**
           * @description SoundCloud Track id
           * @example soundcloud:tracks:1015448728
           */
          track_urn: components["parameters"]["test_track_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Success"];
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
        429: components["responses"]["TooManyRequests"];
      };
    };
    /** Unlikes a track. */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /**
           * @description SoundCloud Track id
           * @example soundcloud:tracks:1015448728
           */
          track_urn: components["parameters"]["test_track_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Success"];
        400: components["responses"]["BadRequest"];
        404: components["responses"]["NotFound"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/likes/playlists/{playlist_urn}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Likes a playlist. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /**
           * @description SoundCloud playlist id
           * @example soundcloud:playlists:1212781357
           */
          playlist_urn: components["parameters"]["playlist_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Success"];
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
        429: components["responses"]["TooManyRequests"];
      };
    };
    /** Unlikes a playlist. */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /**
           * @description SoundCloud playlist id
           * @example soundcloud:playlists:1212781357
           */
          playlist_urn: components["parameters"]["playlist_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Success"];
        400: components["responses"]["BadRequest"];
        404: components["responses"]["NotFound"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reposts/tracks/{track_urn}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reposts a track as the authenticated user */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /**
           * @description SoundCloud Track id
           * @example soundcloud:tracks:1015448728
           */
          track_urn: components["parameters"]["test_track_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    /**
     * Removes a repost on a track as the authenticated user
     * @deprecated
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /**
           * @description SoundCloud Track id
           * @example soundcloud:tracks:1015448728
           */
          track_urn: components["parameters"]["test_track_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reposts/playlists/{playlist_urn}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reposts a playlist as the authenticated user */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /**
           * @description SoundCloud playlist id
           * @example soundcloud:playlists:1205584273
           */
          playlist_urn: components["parameters"]["repost_playlist_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    /** Removes a repost on a playlist as the authenticated user */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /**
           * @description SoundCloud playlist id
           * @example soundcloud:playlists:1205584273
           */
          playlist_urn: components["parameters"]["repost_playlist_urn"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sign-out": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** invalidates session associated with current token */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    OAuthToken: {
      /**
       * @description One of `authorization_code`, `client_credentials`, `refresh_token`
       * @example authorization_code
       * @enum {string}
       */
      grant_type: "authorization_code" | "refresh_token" | "client_credentials";
      /**
       * @description Client ID
       * @example CLIENT_ID
       */
      client_id: string;
      /**
       * @description Client secret
       * @example CLIENT_SECRET
       */
      client_secret: string;
      /**
       * @description Authorization code. Required on `grant_type = authorization_code`.
       * @example 1-123456-12345678-FAbcfbe9ir2wdj0
       */
      code?: string;
      /**
       * @description Redirect URI. Required on `grant_type = (authorization_code|refresh_token)`.
       * @example https://mywebsite/auth/soundcloud
       */
      redirect_uri?: string;
      /**
       * @description Refresh token. Required on `grant_type = refresh_token`.
       * @example 1234c331329477150e7b6056ff212345
       */
      refresh_token?: string;
    };
    TrackMetadataRequest: {
      track?: {
        title?: string;
        permalink?: string;
        /**
         * @default public
         * @enum {string}
         */
        sharing: "public" | "private";
        /**
         * @description who can embed this track "all", "me", or "none"
         * @enum {string}
         */
        embeddable_by?: "all" | "me" | "none";
        purchase_url?: string;
        description?: string;
        genre?: string;
        /** @description The tag_list property contains a list of tags separated by spaces. Multiword tags are quoted in double quotes. We also support machine tags that follow the pattern NAMESPACE:KEY=VALUE. For example: geo:lat=43.555 camel:size=medium “machine:tag=with space” Machine tags are not revealed to the user on the track pages. */
        tag_list?: string;
        label_name?: string;
        release?: string;
        /**
         * write only!
         * @description string, formatted as yyyy-mm-dd, representing release date
         */
        release_date?: string;
        /** @default true */
        streamable: boolean;
        /** @default true */
        downloadable: boolean;
        /**
         * @description Possible values: no-rights-reserved, all-rights-reserved, cc-by, cc-by-nc, cc-by-nd, cc-by-sa, cc-by-nc-nd, cc-by-nc-sa
         * @enum {string}
         */
        license?:
          | "no-rights-reserved"
          | "all-rights-reserved"
          | "cc-by"
          | "cc-by-nc"
          | "cc-by-nd"
          | "cc-by-sa"
          | "cc-by-nc-nd"
          | "cc-by-nc-sa";
        /** @default true */
        commentable: boolean;
        isrc?: string;
      };
    };
    CreateUpdatePlaylistRequest: {
      playlist?: {
        /** @description Title of the playlist */
        title?: string;
        /** @description Description of the playlist */
        description?: string;
        /**
         * @description public or private
         * @enum {string}
         */
        sharing?: "public" | "private";
        /** @description List of tracks to add to playlist */
        tracks?: {
          /** @description SoundCloud track urn */
          urn: string;
        }[];
        /**
         * Only for POST
         * Format: binary
         */
        artwork_data?: string;
        /** @description The European Article Number */
        ean?: string;
        /** @description Playlist's genre */
        genre?: string;
        /** @description Label name */
        label_name?: string;
        /** @description License number */
        license?: string;
        /** @description Playlist's permalink */
        permalink?: string;
        /** @description Full permalink URL */
        permalink_url?: string;
        /** @description Purchase title */
        purchase_title?: string;
        /** @description Purchase URL */
        purchase_url?: string;
        /** @description Playlist's release */
        release?: string;
        /** @description Release date */
        release_date?: string;
        /**
         * @description Playlist or album type
         * @enum {string}
         */
        set_type?: "album" | "playlist";
        /** @description A comma-separated list of tags */
        tag_list?: string;
      };
    };
    CreateUpdatePlaylistFormRequest: {
      "playlist[title]"?: string;
      /**
       * @default public
       * @enum {string}
       */
      "playlist[sharing]": "public" | "private";
      "playlist[description]"?: string;
      /** @description To pass multiple tracks, pass multiple comma-separated values, e.g. -F "playlist[tracks][][urn]=soundcloud:tracks:111,soundcloud:tracks:222" */
      "playlist[tracks][][urn]"?: string;
      /**
       * The playlist artwork in binary format. Supported formats are gif, jpeg and png
       * Format: binary
       */
      "playlist[artwork_data]"?: string;
      "playlist[ean]"?: string;
      "playlist[genre]"?: string;
      "playlist[label_name]"?: string;
      "playlist[license]"?: string;
      "playlist[permalink]"?: string;
      "playlist[permalink_url]"?: string;
      "playlist[purchase_title]"?: string;
      "playlist[purchase_url]"?: string;
      "playlist[release]"?: string;
      "playlist[release_date]"?: string;
      /** @enum {string} */
      "playlist[set_type]"?: "album" | "playlist";
      "playlist[tag_list]"?: string;
    };
    TrackDataRequest: {
      "track[title]"?: string;
      /**
       * Only for uploading
       * Format: binary
       */
      "track[asset_data]"?: string;
      "track[permalink]"?: string;
      /**
       * @default public
       * @enum {string}
       */
      "track[sharing]": "public" | "private";
      /**
       * @description who can embed this track "all", "me", or "none"
       * @enum {string}
       */
      "track[embeddable_by]"?: "all" | "me" | "none";
      "track[purchase_url]"?: string;
      "track[description]"?: string;
      "track[genre]"?: string;
      /** @description The tag_list property contains a list of tags separated by spaces. Multiword tags are quoted in double quotes. We also support machine tags that follow the pattern NAMESPACE:KEY=VALUE. For example: geo:lat=43.555 camel:size=medium “machine:tag=with space” Machine tags are not revealed to the user on the track pages. */
      "track[tag_list]"?: string;
      "track[label_name]"?: string;
      "track[release]"?: string;
      /**
       * write only!
       * @description string, formatted as yyyy-mm-dd, representing release date
       */
      "track[release_date]"?: string;
      /** @default true */
      "track[streamable]": boolean;
      /** @default true */
      "track[downloadable]": boolean;
      /**
       * @description Possible values: no-rights-reserved, all-rights-reserved, cc-by, cc-by-nc, cc-by-nd, cc-by-sa, cc-by-nc-nd, cc-by-nc-sa
       * @enum {string}
       */
      "track[license]"?:
        | "no-rights-reserved"
        | "all-rights-reserved"
        | "cc-by"
        | "cc-by-nc"
        | "cc-by-nd"
        | "cc-by-sa"
        | "cc-by-nc-nd"
        | "cc-by-nc-sa";
      /** @default true */
      "track[commentable]": boolean;
      "track[isrc]"?: string;
      /**
       * Only for uploading, for PRO users
       * Format: binary
       */
      "track[artwork_data]"?: string;
    };
    Found: {
      /** @description Status code. */
      status?: string;
      /** @description Location URL of the resource. */
      location?: string;
    };
    Error: {
      code?: number;
      message?: string;
      link?: string;
      /** @deprecated */
      error?: string | null;
      /** @deprecated */
      errors?: string[];
      /** @deprecated */
      status?: string;
    };
    TooManyRequests: components["schemas"]["Error"] & {
      spam_warning_urn?: string;
    };
    /** @description SoundCloud User object */
    User: {
      /** @description URL to a JPEG image */
      avatar_url?: string;
      /** @description city */
      city?: string;
      /** @description country */
      country?: string;
      /** @description description */
      description?: string;
      /** @description discogs name */
      discogs_name?: string;
      /** @description first name */
      first_name?: string;
      /** @description number of followers */
      followers_count?: number;
      /** @description number of followed users */
      followings_count?: number;
      /** @description first and last name */
      full_name?: string;
      /** @description unique identifier */
      urn?: string;
      /** @description kind of resource */
      kind?: string;
      /**
       * Format: date-time
       * @description profile creation datetime
       */
      created_at?: string;
      /**
       * Format: date-time
       * @description last modified datetime
       */
      last_modified?: string;
      /** @description last name */
      last_name?: string;
      /** @description permalink of the resource */
      permalink?: string;
      /** @description URL to the SoundCloud.com page */
      permalink_url?: string;
      /** @description subscription plan of the user */
      plan?: string;
      /** @description number of public playlists */
      playlist_count?: number;
      /** @description number of favorited public tracks */
      public_favorites_count?: number;
      /** @description number of reposts from user */
      reposts_count?: number;
      /** @description number of public tracks */
      track_count?: number;
      /** @description API resource URL */
      uri?: string;
      /** @description username */
      username?: string;
      /** @description a URL to the website */
      website?: string;
      /** @description a custom title for the website */
      website_title?: string;
      /**
       * @deprecated
       * @description a list subscriptions associated with the user
       */
      subscriptions?: unknown;
    } | null;
    /** @description SoundCloud Me object */
    Me: {
      /** @description URL to a JPEG image. */
      avatar_url?: string;
      /** @description city. */
      city?: string;
      /**
       * @deprecated
       * @description comments count. From now on, the field always has a `0` value.
       */
      comments_count?: number;
      /** @description country. */
      country?: string;
      /** @description created at date */
      created_at?: string;
      /** @description description. */
      description?: string;
      /** @description discogs name. */
      discogs_name?: string;
      /** @description first name. */
      first_name?: string;
      /** @description number of followers. */
      followers_count?: number;
      /** @description number of followed users. */
      followings_count?: number;
      /** @description first and last name. */
      full_name?: string;
      /** @description unique identifier */
      urn?: string;
      /** @description kind of resource. */
      kind?: string;
      /** @description last modified timestamp. */
      last_modified?: string;
      /** @description last name. */
      last_name?: string;
      /** @description likes count. */
      likes_count?: number;
      /** @description locale. */
      locale?: string | null;
      /** @description online. */
      online?: boolean;
      /** @description permalink of the resource. */
      permalink?: string;
      /** @description URL to the SoundCloud.com page. */
      permalink_url?: string;
      /** @description subscription plan of the user. */
      plan?: string;
      /** @description number of public playlists. */
      playlist_count?: number;
      /** @description boolean if email is confirmed. */
      primary_email_confirmed?: boolean;
      /** @description number of private playlists. */
      private_playlists_count?: number;
      /** @description number of private tracks. */
      private_tracks_count?: number;
      /** @description number of favorited public tracks */
      public_favorites_count?: number;
      /** @description user's upload quota */
      quota?: {
        /** @description unlimited upload quota. */
        unlimited_upload_quota?: boolean;
        /** @description upload seconds used. */
        upload_seconds_used?: number;
        /** @description upload seconds left. */
        upload_seconds_left?: number | null;
      };
      /** @description number of reposts from user */
      reposts_count?: number;
      /** @description a list subscriptions associated with the user */
      subscriptions?: unknown;
      /** @description number of public tracks. */
      track_count?: number;
      /** @description upload seconds left. */
      upload_seconds_left?: number | null;
      /** @description API resource URL. */
      uri?: string;
      /** @description username */
      username?: string;
      /** @description a URL to the website. */
      website?: string;
      /** @description a custom title for the website. */
      website_title?: string;
    };
    Users: {
      collection?: components["schemas"]["User"][];
      next_href?: string;
    };
    /** @description Soundcloud Track object. */
    Track: {
      /** @description Track title. */
      title?: string;
      /** @description URL to a JPEG image. */
      artwork_url?: string;
      /** @description Tempo. */
      bpm?: number;
      /** @description Number of comments. */
      comment_count?: number;
      /** @description Is commentable. */
      commentable?: boolean;
      /** @description Created timestamp. */
      created_at?: string;
      /** @description Track description. */
      description?: string;
      /** @description NUmber of downloads. */
      download_count?: number;
      /** @description Is downloadable. */
      downloadable?: string;
      /** @description Track duration. */
      duration?: number;
      /**
       * @deprecated
       * @description Embeddable by.
       */
      embeddable_by?: string;
      /** @description Number of favoritings. */
      favoritings_count?: number;
      /** @description Genre */
      genre?: string;
      /** @description Track identifier. */
      urn?: string;
      /** @description ISRC code. */
      isrc?: string;
      /** @description Key signature. */
      key_signature?: string;
      /** @description Type of object (track). */
      kind?: string;
      /** @description Label user name. */
      label_name?: string;
      /** @description License */
      license?: string;
      /** @description Optional artist name, when different from user. */
      metadata_artist?: string;
      /** @description Permalink URL. */
      permalink_url?: string;
      /** @description Number of plays. */
      playback_count?: number;
      /** @description Purchase title. */
      purchase_title?: string;
      /** @description Purchase URL. */
      purchase_url?: string;
      /** @description Release. */
      release?: string;
      /** @description Day of release. */
      release_day?: number;
      /** @description Month of release. */
      release_month?: number;
      /** @description Year of release. */
      release_year?: number;
      /** @description Type of sharing (public/private). */
      sharing?: string;
      /** @description URL to stream. */
      stream_url?: string;
      /** @description Is streamable. */
      streamable?: boolean;
      /** @description Tags. */
      tag_list?: string;
      /** @description Track URI. */
      uri?: string;
      user?: components["schemas"]["User"] & unknown;
      /** @description Is user's favourite. It is only set when fetching search results or single track, otherwise it is false. */
      user_favorite?: boolean;
      /** @description Number of plays by a user. */
      user_playback_count?: number;
      /** @description Waveform URL. */
      waveform_url?: string;
      /** @description List of countries where track is available. */
      available_country_codes?: string;
      /**
       * @description Level of access the user (logged in or anonymous) has to the track.
       *       * `playable` - user is allowed to listen to a full track.
       *       * `preview` - user is allowed to preview a track, meaning a snippet is available
       *       * `blocked` - user can only see the metadata of a track, no streaming is possible
       * @enum {string|null}
       */
      access?: "playable" | "preview" | "blocked" | null;
      /** @description URL to download a track. */
      download_url?: string;
      /** @description Number of reposts. */
      reposts_count?: number;
      /** @description Secret URL. */
      secret_uri?: string;
    };
    Tracks: {
      collection?: components["schemas"]["Track"][];
      next_href?: string;
    };
    /** @deprecated */
    TracksList: components["schemas"]["Track"][];
    /** @description Soundcloud Playlist Object */
    Playlist: {
      /** @description Playlist title. */
      title?: string;
      /** @description Playlist identifier. */
      urn?: string;
      /** @description Type of Soundcloud object (playlist). */
      kind?: string;
      /** @description URL to a JPEG image. */
      artwork_url?: string;
      /** @description Created timestamp. */
      created_at?: string;
      /** @description Playlist description. */
      description?: string;
      /** @description is downloadable. */
      downloadable?: boolean;
      /** @description Playlist duration. */
      duration?: number;
      /** @description European Article Number. */
      ean?: string;
      /** @description Embeddable by. */
      embeddable_by?: string;
      /** @description Playlist genre. */
      genre?: string;
      /** @description Label user identifier. */
      label_id?: number;
      /** @description Label name. */
      label_name?: string;
      /** @description Last modified timestamp. */
      last_modified?: string;
      /** @description License. */
      license?: string;
      /** @description Playlist permalink. */
      permalink?: string;
      /** @description Playlist permalink URL. */
      permalink_url?: string;
      /** @description Type of playlist. */
      playlist_type?: string;
      /** @description Purchase title. */
      purchase_title?: string;
      /** @description Purchase URL. */
      purchase_url?: string;
      /** @description Release. */
      release?: string;
      /** @description Day of release. */
      release_day?: number;
      /** @description Month of release. */
      release_month?: number;
      /** @description Year of release. */
      release_year?: number;
      /** @description Type of sharing (private/public). */
      sharing?: string;
      /** @description Is streamable. */
      streamable?: boolean;
      /** @description Tags. */
      tag_list?: string;
      /** @description Count of tracks. */
      track_count?: number;
      /** @description List of tracks. */
      tracks?: components["schemas"]["Track"][];
      /** @description Playlist type. */
      type?: string;
      /** @description Playlist URI. */
      uri?: string;
      user?: components["schemas"]["User"];
      /** @description User identifier. */
      user_urn?: string;
      /** @description Count of playlist likes. */
      likes_count?: number;
      label?: (Record<string, never> | null) & components["schemas"]["User"];
      /** @description tracks URI. */
      tracks_uri?: string | null;
      /** @description Tags. */
      tags?: string | null;
    };
    Playlists: {
      collection?: components["schemas"]["Playlist"][];
      next_href?: string;
    };
    /** @deprecated */
    PlaylistsArray: components["schemas"]["Playlist"][];
    /** @description User's activities. */
    Activities: {
      collection?: {
        /** @description Type of activity (track). */
        type?: string;
        /** @description Created timestamp. */
        created_at?: string;
        /** @description Origin. */
        origin?: components["schemas"]["Track"] | components["schemas"]["Playlist"];
      }[];
      next_href?: string;
      future_href?: string;
    };
    /** @description User's links added to their profile */
    WebProfiles: {
      /** @description Timestamp of when the link was added to the profile. */
      created_at?: string;
      /** @description Id */
      urn?: string;
      /** @description Kind */
      kind?: string;
      /** @description Service or platform */
      service?: string;
      /** @description Link's title */
      title?: string;
      /** @description URL of the external link */
      url?: string;
      /** @description Username extracted from the external link */
      username?: string;
    }[];
    /** @description User's Comment */
    Comment: {
      /** @description Comment body. */
      body?: string;
      /** @description Created timestamp. */
      created_at?: string;
      /** @description Identifier. */
      urn?: string;
      /** @description Kind (comment). */
      kind?: string;
      /** @description User's identifier. */
      user_urn?: string;
      /** @description Timestamp. */
      timestamp?: string;
      /** @description Track's identifier. */
      track_urn?: string;
      /** @description Comment's URL. */
      uri?: string;
      /** @description SoundCloud User object */
      user?: {
        /** @description unique identifier */
        urn?: string;
        /** @description kind of resource. */
        kind?: string;
        /** @description permalink of the resource. */
        permalink?: string;
        /** @description username */
        username?: string;
        /** @description last modified timestamp. */
        last_modified?: string;
        /** @description API resource URL. */
        uri?: string;
        /** @description URL to the SoundCloud.com page. */
        permalink_url?: string;
        /** @description URL to a JPEG image. */
        avatar_url?: string;
        /** @description number of followers. */
        followers_count?: number;
        /** @description number of followed users. */
        followings_count?: number;
        /** @description number of reposts from user */
        reposts_count?: number;
      };
    };
    Comments: {
      collection?: components["schemas"]["Comment"][];
      next_href?: string | null;
    };
    Streams: {
      hls_aac_160_url?: string;
      /** @deprecated */
      http_mp3_128_url?: string;
      hls_mp3_128_url?: string;
      /** @deprecated */
      hls_opus_64_url?: string;
      preview_mp3_128_url?: string;
    };
  };
  responses: {
    /** @description Success */
    Success: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8": unknown;
      };
    };
    /** @description Success */
    Successful: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8": unknown;
      };
    };
    /** @description Accepted */
    Accepted: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8": unknown;
      };
    };
    /** @description Found */
    Found: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8": components["schemas"]["Found"];
      };
    };
    /** @description Found */
    FoundHtml: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8": string;
      };
    };
    /** @description Created */
    Created: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8": unknown;
      };
    };
    /** @description Bad Request */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8": components["schemas"]["Error"];
      };
    };
    /** @description Unauthorized */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8": components["schemas"]["Error"];
      };
    };
    /** @description Forbidden */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Not Found */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Unprocessable Entity */
    UnprocessableEntity: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Too Many Requests */
    TooManyRequests: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["TooManyRequests"];
      };
    };
    /** @description Success */
    User: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8": components["schemas"]["User"];
      };
    };
    /** @description Success */
    Me: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8": components["schemas"]["Me"];
      };
    };
    /** @description Success */
    Users: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8": components["schemas"]["Users"];
      };
    };
    /** @description Success */
    Track: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8": components["schemas"]["Track"];
      };
    };
    /** @description Success */
    Tracks: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8":
          | components["schemas"]["Tracks"]
          | components["schemas"]["TracksList"];
      };
    };
    /** @description Success */
    TracksList: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8": components["schemas"]["TracksList"];
      };
    };
    /** @description Success */
    Playlist: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8": components["schemas"]["Playlist"];
      };
    };
    /** @description Success */
    Playlists: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8":
          | components["schemas"]["Playlists"]
          | components["schemas"]["PlaylistsArray"];
      };
    };
    /** @description Success */
    Activities: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8": components["schemas"]["Activities"];
      };
    };
    /** @description Success */
    WebProfiles: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8": components["schemas"]["WebProfiles"];
      };
    };
    /** @description Success */
    Comment: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8": components["schemas"]["Comment"];
      };
    };
    /** @description Success */
    Comments: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8": components["schemas"]["Comments"];
      };
    };
    /** @description Success */
    Streams: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json; charset=utf-8": components["schemas"]["Streams"];
      };
    };
  };
  parameters: {
    /** @description Return tracks with a specified bpm[from], bpm[to] */
    bpm: {
      /**
       * @description Return tracks with at least this bpm value
       * @example 123
       */
      from?: number;
      /**
       * @description Return tracks with at most this bpm value
       * @example 456
       */
      to?: number;
    };
    /**
     * @description The client id belonging to your application
     * @example some client
     */
    client_id: string;
    /** @description (yyyy-mm-dd hh:mm:ss) return tracks created within the specified dates */
    created_at: {
      /**
       * @description (yyyy-mm-dd hh:mm:ss) return tracks created at this date or later
       * @example 2020-12-24 00:00:00
       */
      from?: string;
      /**
       * @description (yyyy-mm-dd hh:mm:ss) return tracks created at this date or earlier
       * @example 2020-12-26 00:00:00
       */
      to?: string;
    };
    /** @description Return tracks within a specified duration range */
    duration: {
      /**
       * @description Return tracks with at least this duration value
       * @example 123456
       */
      from?: number;
      /**
       * @description Return tracks with at most this duration value
       * @example 456789
       */
      to?: number;
    };
    /**
     * @description A comma separated list of genres
     * @example Pop,House
     */
    genres: string;
    /**
     * @description A comma separated list of track ids to filter on
     * @example 1,2,3
     */
    ids: string;
    /**
     * @description A comma separated list of track urns to filter on
     * @example soundcloud:tracks:1,soundcloud:tracks:2,soundcloud:tracks:3
     */
    urns: string;
    /**
     * @description Number of results to return in the collection.
     * @example 2
     */
    limit: number;
    /**
     * @deprecated
     * @description Offset of first result. Deprecated, use `linked_partitioning` instead.
     * @example 0
     */
    offset: number;
    /**
     * @description search
     * @example hello
     */
    q: string;
    /**
     * @description The redirect uri you have configured for your application
     * @example https://soundcloud.com
     */
    redirect_uri: string;
    /**
     * @description Support only the Authorization Code Flow
     * @example code
     */
    response_type: "code";
    /**
     * @description Scope. Leave blank by default
     * @example default
     */
    scope: string;
    /**
     * @description Any value included here will be appended to the redirect URI. Use this for CSRF protection.
     * @example encrypted_session_info
     */
    state: string;
    /**
     * @description A comma separated list of tags
     * @example test
     */
    tags: string;
    /**
     * @description SoundCloud URL
     * @example https://soundcloud.com/user-434241656
     */
    url: string;
    /**
     * @description Returns paginated collection of items (recommended, returning a list without pagination is deprecated and should not be used)
     * @example true
     */
    linked_partitioning: boolean;
    /** @description A secret token to fetch private playlists/tracks */
    secret_token: string;
    /** @description Filters content by level of access the user (logged in or anonymous) has to the track. The result list will include only tracks with the specified access. Include all options if you'd like to see all possible tracks. See `Track#access` schema for more details. */
    access: ("playable" | "preview" | "blocked")[];
    /** @description Filters content by level of access the user (logged in or anonymous) has to the track. The result list will include only tracks with the specified access. Include all options if you'd like to see all possible tracks. See `Track#access` schema for more details. */
    access_explicit: ("playable" | "preview" | "blocked")[];
    /**
     * @description A boolean flag to request a playlist with or without tracks. Default is `true`.
     * @example true
     */
    show_tracks: boolean;
    /**
     * @description SoundCloud comment urn
     * @example soundcloud:comments:123456
     */
    comment_urn: string;
    /**
     * @description SoundCloud User id to denote a Follower
     * @example soundcloud:users:743372812
     */
    follower_urn: string;
    /**
     * @description SoundCloud User id to denote a Following of a user
     * @example soundcloud:users:25219981
     */
    following_urn: string;
    /**
     * @description SoundCloud playlist id
     * @example soundcloud:playlists:1212781357
     */
    playlist_urn: string;
    /**
     * @description SoundCloud playlist id
     * @example soundcloud:playlists:10
     */
    fake_playlist_urn: string;
    /**
     * @description SoundCloud playlist id
     * @example soundcloud:playlists:1205584273
     */
    repost_playlist_urn: string;
    /**
     * @description tag
     * @example some tag
     */
    tag: string;
    /**
     * @description SoundCloud Track urn
     * @example soundcloud:tracks:308946187
     */
    track_urn: string;
    /**
     * @description SoundCloud Track id
     * @example soundcloud:tracks:1015448728
     */
    test_track_urn: string;
    /**
     * @description SoundCloud User id
     * @example soundcloud:users:948745750
     */
    user_urn: string;
    /**
     * @description SoundCloud User id
     * @example soundcloud:users:743372812
     */
    user_urn_to_follow: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
