export const ENV = {
	VITE_APP_SOUNDCLOUD_CLIENT_ID: import.meta.env['VITE_APP_SOUNDCLOUD_CLIENT_ID']!,
	VITE_APP_SOUNDCLOUD_CLIENT_SECRET: import.meta.env['VITE_APP_SOUNDCLOUD_CLIENT_SECRET']!,
	VITE_APP_SOUNDCLOUD_REDIRECT_URL: import.meta.env['VITE_APP_SOUNDCLOUD_REDIRECT_URL']!
};
